[package]
name = "milleniumdb_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4.8", features = ["derive"] }
humantime = { version = "2.1.0" }
futures = "0.3.30"